apiVersion: apps/v1
kind: Deployment
metadata:
  name: "sonar-deployment"
  namespace: default
  labels:
    app: "sonar"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "sonar"
  template:
    metadata:
      labels:
        app: "sonar"
    spec:
      imagePullSecrets:
      - name: harborcred
      containers:
        image: registry.kocsistem.com.tr/devops/sonarqubespring:v1
        imagePullPolicy: Always
        name: "sonar"
        ports:
        - containerPort: 8081
          name: "sonar"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: tz-istanbul
          mountPath: /etc/localtime
      volumes:
      - name: tz-istanbul
        hostPath:
          path: /usr/share/zoneinfo/Europe/Istanbul
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  namespace: default
  labels:
    app: sonar
spec:
  type: NodePort
  selector:
    app: sonar
  ports:
  - name: "8081"
    targetPort: 8081
    port: 8081
    nodePort: 30104